# Numpy Exercise



### Name-Shruti Deepak Jadhav

 ### 1. Import the numpy package under the name as np

In [3]:
import numpy as np

### 2. Print the numpy version and the configuration

In [4]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Deepak J/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Deepak J/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Deepak J/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Deepak J/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Deepak J/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Deepak J/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Deepak J/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Deepak J/anaconda3\\Library\\include']
None


### 3. Create a null vector of size 10

In [5]:
arr =  np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


###  4.How to find the memory size of any array


In [7]:
a = arr.size
print(a)

10


### 5. How to get the documentation of the numpy add function from the command line?


In [9]:
np.add?

### 6. Create a null vector of size 10 but the fifth value which is 1


In [11]:
arr = np.zeros(10)
arr [4]= 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7. Create a vector with values ranging from 10 to 49

In [13]:
arr = np.arange(10,50,5)
print(arr)

[10 15 20 25 30 35 40 45]


### 8. Reverse a vector (first element becomes last)

In [14]:
np.flipud(arr)

array([45, 40, 35, 30, 25, 20, 15, 10])

### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [17]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Create an array of 10 fives¶

In [18]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

### Create an array of all the even integers from 10 to 50¶

In [19]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

### Create a 3x3 identity matrix¶

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [22]:
np.random.randn(27)

array([ 0.18184165, -1.47222015,  0.39271254, -1.75539522, -1.3658144 ,
       -0.0874952 ,  0.91617911, -0.52346872,  0.81190325, -0.12063867,
       -0.79827887, -1.23747646,  0.80089008,  0.32171366,  0.94723046,
       -0.63929539,  0.80793946,  0.77358735, -1.68928537,  1.20096247,
        0.45036722, -0.09174143, -0.35808047,  0.06719499,  1.5980924 ,
        0.06410036,  2.89939398])

### 10. Find indices of non-zero elements from [1,2,0,0,4,0]


In [24]:
arr = np.array([1,2,0,0,4,0])
#ans = np.where(arr==0)
ans =  np.nonzero(arr)
print(ans)


(array([0, 1, 4], dtype=int64),)


### 11 . Create a 3x3 identity matrix

In [26]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 12 . Create a 3x3*3 identity matrix with random value

In [28]:
np.random.random((3,3,3))

array([[[0.0883191 , 0.4047007 , 0.47362692],
        [0.91873839, 0.22264941, 0.07846458],
        [0.48893924, 0.89720498, 0.07917837]],

       [[0.05072209, 0.09713382, 0.58512873],
        [0.49993798, 0.55553092, 0.45866748],
        [0.07281293, 0.53330949, 0.49548939]],

       [[0.18418797, 0.55201004, 0.23814819],
        [0.42967733, 0.93763039, 0.24811921],
        [0.61287667, 0.91921174, 0.04280679]]])

### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [31]:
arr = np.random.random((10,10))
a = arr.max()
b = arr.min()
print(a,b,sep="\n")

0.9871034848301211
0.02479669461644496


### 14.Create a random vector of size 30 and find the mean value

In [38]:
arr = np.ones(30)
print(arr)
a = np.mean(arr)
print("mean value :",a)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.]
mean value : 1.0


### 15. Create a 2d array with 1 on the border and 0 inside

In [39]:
ans = np.ones((5,5))
ans[1:-1,1:-1] = 0
ans

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [3]:
import numpy as np

In [14]:
ans = np.diag([1,2,3,4],-1)
print(ans)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [24]:
ans = np.zeros((8,8),dtype=int)
ans[1::2,::2] = 1
ans[::2,1::2] = 1
ans

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [25]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)

### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [26]:
 arr= [[0,1],[1,0]]
a=4
b= 4
repetition = (a,b)
ans = np.tile(arr,repetition)
ans

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [29]:
a = np.random.random((5,3))
b = np.random.random((3,2))
print(np.dot(a,b))

[[1.29318217 0.76396596]
 [1.08174294 0.60746603]
 [1.03409122 0.58761881]
 [0.79614379 0.45834304]
 [1.09967038 0.69245906]]


### 25. . How to find common values between two arrays?

In [35]:
arr1 = [[1, 2,9], [3, 4.,5]]
arr2 = [[5, 4, 7], [2, 9, 10]]

np.intersect1d(arr1, arr2)

array([2., 4., 5., 9.])

### 26.How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [36]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2021-05-24
Today:  2021-05-25
Tomorrow:  2021-05-26


### 27.Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
[ ]


In [37]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 28.Create a vectore of size 10 and sort it

In [38]:
arr = np.random.uniform(0,10,10)
arr.sort()
arr

array([0.17729859, 0.61805231, 0.99997428, 2.40758502, 3.31808665,
       4.57589184, 5.44656022, 6.65710899, 6.83367766, 7.36203249])

### 29.How to sum a small array faster than np.sum? (★★☆)

In [40]:
arr= np.arange(10)
np.add.reduce(arr)

45

### 30.How to swap two rows of an array? 

In [43]:
A = np.arange(25).reshape(5,5)
A[[1,3]] = A[[3,1]]
print(A)

[[ 0  1  2  3  4]
 [15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [20 21 22 23 24]]
